#ifndef TRACY_HCOM_CONFIG_HPP
#define TRACY_HCOM_CONFIG_HPP

// TracyHcomConfig.hpp
// Feature-gate macros for the Hcom bundle.
// Set these via compiler definitions or CMake options before including any
// Hcom header; do not edit this file directly.

// ── Perfetto export ──────────────────────────────────────────────────────────
// Define TRACYHCOM_ENABLE_PERFETTO (or pass -DTRACYHCOM_ENABLE_PERFETTO=1) to
// compile in the Perfetto native exporter (TracyLitePerfetto.cpp).
// Requires perfetto.h on the include path when enabled.
#if defined(TRACYHCOM_ENABLE_PERFETTO)
#  define TRACYLITE_PERFETTO
#endif

// ── Text chunk transport ─────────────────────────────────────────────────────
// TracyLiteChunkWriter.hpp is header-only and always compiled in.
// No extra define is required.

// ── Phase-one: TracyProfiler dependency ─────────────────────────────────────
// In phase one the bundle still uses tracy::Profiler::GetTime() from
// TracyProfiler.hpp.  This will be replaced by a slim TracyHcomTime.hpp shim
// in phase two.  Set TRACYHCOM_NO_TRACY_PROFILER to opt-in to the phase-two
// shim once it exists.
#if defined(TRACYHCOM_NO_TRACY_PROFILER)
#  define TRACYHCOM_USE_HCOM_TIME
#endif

#endif // TRACY_HCOM_CONFIG_HPP
