if (NOT NO_ISA_EXTENSIONS)
    include(CheckCXXCompilerFlag)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm64")
        CHECK_CXX_COMPILER_FLAG("-mcpu=native" COMPILER_SUPPORTS_MCPU_NATIVE)
        if(COMPILER_SUPPORTS_MARCH_NATIVE)
            add_compile_options(-mcpu=native)
        endif()
    else()
        CHECK_CXX_COMPILER_FLAG("-march=native" COMPILER_SUPPORTS_MARCH_NATIVE)
        if(COMPILER_SUPPORTS_MARCH_NATIVE)
            add_compile_options(-march=native)
        endif()
    endif()
    if(WIN32)
        add_compile_options(/arch:AVX2)
    endif()
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT LEGACY)
    set(USE_WAYLAND ON)
else()
    set(USE_WAYLAND OFF)
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
        if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "15")
          message(FATAL_ERROR "Apple Clang 15 or newer is required.")
        elseif(NOT CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "16")
          # AppleClang 15 has issues with to_chars in <chrono> if target is too old
          add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-mmacosx-version-min=13.3>)
        endif()
        add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-fexperimental-library>)
    endif()
endif()

if(WIN32)
    add_definitions(-DNOMINMAX -DWIN32_LEAN_AND_MEAN -D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR)
    # /MP is MSVC-specific for multi-processor compilation
    if(MSVC)
        add_compile_options(/MP /utf-8)
        if(CMAKE_GENERATOR MATCHES "Ninja")
            get_filename_component(TRACY_MSVC_BIN_DIR "${CMAKE_CXX_COMPILER}" DIRECTORY)
            get_filename_component(TRACY_MSVC_ROOT_DIR "${TRACY_MSVC_BIN_DIR}/../../.." ABSOLUTE)
            set(TRACY_MSVC_LIB_DIR "${TRACY_MSVC_ROOT_DIR}/lib/x64")
            if(EXISTS "${TRACY_MSVC_LIB_DIR}")
                link_directories("${TRACY_MSVC_LIB_DIR}")
            endif()

            if(CMAKE_RC_COMPILER)
                get_filename_component(TRACY_SDK_BIN_ARCH_DIR "${CMAKE_RC_COMPILER}" DIRECTORY)
                get_filename_component(TRACY_SDK_BIN_VER_DIR "${TRACY_SDK_BIN_ARCH_DIR}" DIRECTORY)
                get_filename_component(TRACY_SDK_BIN_DIR "${TRACY_SDK_BIN_VER_DIR}" DIRECTORY)
                get_filename_component(TRACY_SDK_ROOT_DIR "${TRACY_SDK_BIN_DIR}" DIRECTORY)
                get_filename_component(TRACY_SDK_VERSION "${TRACY_SDK_BIN_VER_DIR}" NAME)

                set(TRACY_SDK_UCRT_LIB_DIR "${TRACY_SDK_ROOT_DIR}/lib/${TRACY_SDK_VERSION}/ucrt/x64")
                set(TRACY_SDK_UM_LIB_DIR "${TRACY_SDK_ROOT_DIR}/lib/${TRACY_SDK_VERSION}/um/x64")

                if(EXISTS "${TRACY_SDK_UCRT_LIB_DIR}")
                    link_directories("${TRACY_SDK_UCRT_LIB_DIR}")
                endif()
                if(EXISTS "${TRACY_SDK_UM_LIB_DIR}")
                    link_directories("${TRACY_SDK_UM_LIB_DIR}")
                endif()
            endif()
        endif()
    endif()
endif()

if(EMSCRIPTEN)
    add_compile_options(-pthread -DIMGUI_IMPL_OPENGL_ES2)
endif()

if(NOT CMAKE_BUILD_TYPE STREQUAL "Debug" AND NOT EMSCRIPTEN)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
endif()

if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
    find_program(MOLD_LINKER mold)
    if(MOLD_LINKER)
        set(CMAKE_LINKER_TYPE "MOLD")
    endif()
    if (CMAKE_BUILD_TYPE STREQUAL "Debug")
        add_compile_options(-fno-eliminate-unused-debug-types)
    endif()
endif()

find_program(CCACHE ccache)
if(CCACHE)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache) 
endif()

file(GENERATE OUTPUT .gitignore CONTENT "*")

set(CMAKE_COLOR_DIAGNOSTICS ON)
